# Generated by Django 6.0.5 on 2026-06-10 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('hex_code', models.CharField(max_length=10, unique=True, verbose_name='Hex Code')),
            ],
        ),
        migrations.CreateModel(
            name='Attire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attires', to='accounts.avatar', verbose_name='Avatar')),
                ('clothing_pieces', models.ManyToManyField(related_name='attires', to='attires.clothingpiece', verbose_name='Clothing pieces')),
                ('colors', models.ManyToManyField(related_name='attires', to='attires.color', verbose_name='Colors')),
            ],
            options={
                'verbose_name': 'Attire',
                'verbose_name_plural': 'Attires',
            },
        ),
    ]
