# Generated by Django 6.0.5 on 2026-08-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('name',), 'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
    ]
