# Generated by Django 6.0.5 on 2026-07-04 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_done', models.BooleanField(default=False, verbose_name='is done')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('type', models.CharField(blank=True, choices=[('groceries', 'Groceries'), ('travel', 'Travel'), ('work', 'Work'), ('school', 'School'), ('chores', 'Chores'), ('sports', 'Sports')], max_length=20, null=True, verbose_name='type')),
                ('appointed_points', models.PositiveSmallIntegerField(default=1, verbose_name='appointed points')),
                ('accomplished_at', models.DateTimeField(blank=True, null=True, verbose_name='accomplished at')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='due date')),
                ('alarm_at', models.DateTimeField(blank=True, null=True, verbose_name='alarm at')),
                ('timer_duration', models.DurationField(blank=True, null=True, verbose_name='timer duration')),
                ('timer_at', models.DateTimeField(blank=True, null=True, verbose_name='timer at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='units.unit', verbose_name='unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='zones.zone', verbose_name='zone')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_done', False)), fields=('user', 'unit', 'name', 'zone'), name='unique_active_task_per_user_unit_zone')],
            },
        ),
    ]
