# Generated by Django 6.0.5 on 2026-09-25 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_done', models.BooleanField(default=False, verbose_name='is done')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('type', models.CharField(blank=True, choices=[('groceries', 'Groceries'), ('workout', 'Workout'), ('chores', 'Chores'), ('list', 'List')], max_length=20, null=True, verbose_name='type')),
                ('appointed_points', models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='appointed points')),
                ('accomplished_at', models.DateTimeField(blank=True, null=True, verbose_name='accomplished at')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='due date')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='units.unit', verbose_name='unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['is_done', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('is_done', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('quantity', models.CharField(blank=True, max_length=50, verbose_name='quantity')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='tasks.task', verbose_name='task')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('is_done', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('reps', models.CharField(blank=True, max_length=100)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='tasks.task', verbose_name='task')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'abstract': False,
            },
        ),
    ]
