# Generated by Django 6.0.5 on 2026-07-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='alarm_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='timer_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='timer_duration',
        ),
    ]
