# Generated by Django 6.0.5 on 2026-06-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='brand',
        ),
    ]
