# Generated by Django 6.0.5 on 2026-09-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_active_task_per_user_unit',
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, choices=[('groceries', 'Groceries'), ('workout', 'Workout'), ('chores', 'Chores'), ('list', 'List')], max_length=20, null=True, verbose_name='type'),
        ),
    ]
