# Generated by Django 6.0.5 on 2026-09-14 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('is_done', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('buying_frequency', models.TimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.task', verbose_name='task')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
    ]
