# Generated by Django 6.0.5 on 2026-09-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_groceryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceryitem',
            options={'ordering': ['position', 'pk']},
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='buying_frequency',
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='tasks.task', verbose_name='task'),
        ),
    ]
