# Generated by Django 6.0.5 on 2026-08-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_alarm_at_remove_task_timer_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='appointed_points',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='appointed points'),
        ),
    ]
