# Generated by Django 6.0.5 on 2026-09-30 20:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_choreitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreitem',
            name='frequency_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Frequency days'),
        ),
        migrations.AlterField(
            model_name='choreitem',
            name='last_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last done at'),
        ),
        migrations.AlterField(
            model_name='choreitem',
            name='minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Minutes'),
        ),
        migrations.AlterField(
            model_name='choreitem',
            name='room',
            field=models.CharField(blank=True, choices=[('', 'Section'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('bedroom', 'Bedroom'), ('living', 'Living room'), ('outdoor', 'Outdoor')], max_length=100, verbose_name='Room'),
        ),
        migrations.CreateModel(
            name='ChoreCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chore_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tasks.choreitem', verbose_name='Duty')),
            ],
            options={
                'ordering': ('-done_at',),
            },
        ),
    ]
