# Generated by Django 6.0.5 on 2026-10-04 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_choreitem_frequency_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('is_done', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='tasks.task', verbose_name='task')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'abstract': False,
            },
        ),
    ]
