# Generated by Django 6.0.5 on 2026-09-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_groceryitem_options_remove_groceryitem_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, verbose_name='quantity'),
        ),
    ]
