# Generated by Django 6.0.5 on 2026-06-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, null=True, unique=True, verbose_name='Slug')),
                ('scene_position', models.JSONField(blank=True, default=dict, verbose_name='Scene position')),
            ],
        ),
    ]
