# Generated by Django 6.0.5 on 2026-07-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(blank=True, null=True, verbose_name='Species')),
                ('hair_color', models.CharField(blank=True, null=True, verbose_name='Hair Color')),
                ('glasses', models.BooleanField(default=False, verbose_name='Glasses')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='Points')),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
            },
        ),
    ]
