# Generated by Django 6.0.5 on 2026-06-01 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attires', '0001_initial'),
        ('tasks', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Age')),
                ('species', models.CharField(blank=True, null=True, verbose_name='Species')),
                ('hair_color', models.CharField(blank=True, null=True, verbose_name='Hair Color')),
                ('glasses', models.BooleanField(default=False, verbose_name='Glasses')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='Points')),
                ('attire', models.ManyToManyField(blank=True, null=True, related_name='avatars', to='attires.attire', verbose_name='Attire')),
                ('tasks', models.ManyToManyField(related_name='avatars', to='tasks.task', verbose_name='Tasks')),
                ('units', models.ManyToManyField(related_name='avatars', to='units.unit', verbose_name='Units')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
            },
        ),
    ]
