# Generated by Django 6.0.5 on 2026-06-01 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='age',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='units',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
