# Generated by Django 6.0.5 on 2026-09-09 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationread',
            name='last_read_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
