# Generated by Django 6.0.5 on 2026-07-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is read'),
        ),
    ]
