# Generated by Django 6.0.5 on 2026-07-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0003_remove_message_is_read_messageread'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
