# Generated by Django 6.0.5 on 2026-08-24 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0004_message_title'),
        ('tasks', '0003_alter_task_appointed_points'),
        ('units', '0002_alter_unit_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='message',
            name='related_task',
        ),
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
        migrations.RemoveField(
            model_name='message',
            name='unit',
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tasks.task', verbose_name='Task')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='units.unit', verbose_name='Unit')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='comms.conversation', verbose_name='Conversation'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ConversationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='comms.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_reads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('unit', 'task'), name='unique_task_conversation'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('task__isnull', True)), fields=('unit',), name='unique_general_conversation'),
        ),
        migrations.AddConstraint(
            model_name='conversationread',
            constraint=models.UniqueConstraint(fields=('user', 'conversation'), name='unique_conversation_read'),
        ),
    ]
