# Generated by Django 6.0.5 on 2026-08-24 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0005_alter_message_options_remove_message_recipients_and_more'),
        ('units', '0002_alter_unit_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='units.unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='conversationread',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='comms.conversation'),
        ),
        migrations.AlterField(
            model_name='conversationread',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_reads', to=settings.AUTH_USER_MODEL),
        ),
    ]
